rules:
  type-enum:
    - 2
    - always
    - - build
      - chore
      - ci
      - docs
      - feat
      - fix
      - perf
      - refactor
      - revert
      - style
      - test
      - flake
      - treewide
  type-case: [2, always, lower-case]
  scope-case: [2, always, lower-case]
  scope-empty: [0]
  subject-case: [2, always, lower-case]
  body-empty: [0, always]
