on:
  - push
jobs:
  build-all:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v24
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: docker/setup-qemu-action@v3
        with:
          platforms: aarch64
      - run: nix run nixpkgs#just build-all
