on:
  - push
jobs:
  check-linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v24
      - uses: docker/setup-qemu-action@v3
        with:
          platforms: aarch64
      - run: nix run nixpkgs#just check
